Split scripts
Because Deno.emit function not exists on Deno Deploy

```
TypeError: Deno.emit is not a function
    at buildClient (file:///src/script/build.ts:3:35)
    at file:///src/index.ts:3:7
```